# Generated by Django 5.0.1 on 2024-03-18 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0002_question_answer_text2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer_text2',
        ),
    ]
