# Generated by Django 5.0.1 on 2024-03-18 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0003_remove_question_answer_text2'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='answer_text2',
            field=models.TextField(null=True),
        ),
    ]
