# Generated by Django 5.0.1 on 2024-03-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0005_remove_question_answer_text_question_answer_correct_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='answer_text1',
            new_name='answer_1',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text2',
            new_name='answer_2',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text3',
            new_name='answer_3',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_text4',
            new_name='answer_4',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='answer_correct',
            new_name='correct_Answer',
        ),
        migrations.RenameField(
            model_name='question',
            old_name='question_text',
            new_name='question',
        ),
    ]
