# Generated by Django 5.0.1 on 2024-03-31 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0006_rename_answer_text1_question_answer_1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_Answer',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default=1, max_length=1, null=True),
        ),
    ]
