# Generated by Django 5.0.1 on 2024-04-01 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eduprod', '0007_alter_question_correct_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer_1',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_2',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_3',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='answer_4',
            field=models.TextField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_Answer',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4)], default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=150),
        ),
    ]
